name: Build and Package WinUI 3 App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Project_Path: aniliberty/aniliberty.csproj
      Configuration: Release
      Platform: x64

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Восстанавливаем пакеты строго для целевого проекта и платформы x64
    - name: Restore NuGet Packages
      run: |
        msbuild ${{ env.Project_Path }} `
          -t:Restore `
          /p:Configuration=${{ env.Configuration }} `
          /p:Platform=${{ env.Platform }} `
          /p:RuntimeIdentifier=win-${{ env.Platform }}

    - name: Decode Signing Certificate
      shell: powershell
      run: |
        if ("${{ secrets.BASE64_PFX }}" -ne "") {
          $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.BASE64_PFX }}")
          [System.IO.File]::WriteAllBytes("${{ github.workspace }}\GitHubActionsWorkflow.pfx", $pfx_cert_byte)
        }

    - name: Build and Package MSIX
      run: |
        msbuild ${{ env.Project_Path }} `
          /p:Configuration=${{ env.Configuration }} `
          /p:Platform=${{ env.Platform }} `
          /p:RuntimeIdentifier=win-${{ env.Platform }} `
          /p:GenerateAppxPackageOnBuild=true `
          /p:AppxPackageSigningEnabled=true `
          /p:UapAppxPackageBuildMode=SideloadOnly `
          /p:AppxBundle=Never `
          /p:PackageCertificateKeyFile="${{ github.workspace }}\GitHubActionsWorkflow.pfx" `
          /p:PackageCertificatePassword="${{ secrets.PFX_PASSWORD }}"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WinUI3-MSIX-Package
        path: aniliberty/AppPackages/ # Путь к папке AppPackages относительно корня
